---
name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 20.x
        uses: actions/setup-node@v3
        with:
          node-version: 20.x        
          path: ~/.npm          

      - run: npm install nbb
      - run: npm install
      - run: npx nbb compile.cljs
      - run: npx nbb compile.cljs --format html
      - name: Deploy
        uses: s0/git-publish-subdir-action@develop
        env:
          REPO: self
          BRANCH: build
          FOLDER: target
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}